# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `font-awesome-sass` gem.
# Please instead update this file by running `bin/tapioca gem font-awesome-sass`.

# source://font-awesome-sass//lib/font-awesome-sass.rb#1
module FontAwesome; end

# source://font-awesome-sass//lib/font-awesome-sass.rb#2
module FontAwesome::Sass
  class << self
    # source://font-awesome-sass//lib/font-awesome-sass.rb#27
    def assets_path; end

    # @return [Boolean]
    #
    # source://font-awesome-sass//lib/font-awesome-sass.rb#39
    def deprecated_sass?; end

    # source://font-awesome-sass//lib/font-awesome-sass.rb#23
    def fonts_path; end

    # Paths
    #
    # source://font-awesome-sass//lib/font-awesome-sass.rb#15
    def gem_path; end

    # source://font-awesome-sass//lib/font-awesome-sass.rb#4
    def load!; end

    # @return [Boolean]
    #
    # source://font-awesome-sass//lib/font-awesome-sass.rb#35
    def rails?; end

    # @return [Boolean]
    #
    # source://font-awesome-sass//lib/font-awesome-sass.rb#31
    def sprockets?; end

    # source://font-awesome-sass//lib/font-awesome-sass.rb#19
    def stylesheets_path; end

    private

    # source://font-awesome-sass//lib/font-awesome-sass.rb#46
    def register_rails_engine; end

    # source://font-awesome-sass//lib/font-awesome-sass.rb#51
    def register_sprockets; end
  end
end

# source://font-awesome-sass//lib/font_awesome/sass/rails/engine.rb#3
module FontAwesome::Sass::Rails; end

# source://font-awesome-sass//lib/font_awesome/sass/rails/engine.rb#4
class FontAwesome::Sass::Rails::Engine < ::Rails::Engine
  class << self
    # source://activesupport/7.0.4.3/lib/active_support/callbacks.rb#68
    def __callbacks; end
  end
end

# source://font-awesome-sass//lib/font_awesome/sass/rails/railtie.rb#6
class FontAwesome::Sass::Rails::Railtie < ::Rails::Railtie; end

# source://font-awesome-sass//lib/font_awesome/sass/rails/helpers.rb#4
module FontAwesome::Sass::Rails::ViewHelpers
  # source://font-awesome-sass//lib/font_awesome/sass/rails/helpers.rb#5
  def icon(style, name, text = T.unsafe(nil), html_options = T.unsafe(nil)); end
end
