// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DateRangeController from "./date_range_controller"
application.register("date-range", DateRangeController)

import MapboxPlacesAutocompleteController from "./mapbox_places_autocomplete_controller"
application.register("mapbox-places-autocomplete", MapboxPlacesAutocompleteController)
