// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CalculateTotalDistanceAndDurationController from "./calculate_total_distance_and_duration_controller"
application.register("calculate-total-distance-and-duration", CalculateTotalDistanceAndDurationController)

import DateRangeController from "./date_range_controller"
application.register("date-range", DateRangeController)
