# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RecalculateTripJob`.
# Please instead update this file by running `bin/tapioca dsl RecalculateTripJob`.

class RecalculateTripJob
  class << self
    sig { returns(T.any(RecalculateTripJob, FalseClass)) }
    def perform_later; end

    sig { returns(T.untyped) }
    def perform_now; end
  end
end
